name = "invoice-worker"

main = "src/workers/worker.js"

compatibility_date = "2024-12-11"

[triggers]
crons = ["*/1 * * * *"]

[vars]
GOOGLE_SERVICE_ACCOUNT_EMAIL="invoice-gen-wrangler@invoice-gen-482414.iam.gserviceaccount.com"
GOOGLE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC0ZPctmg+fz9zd\nCMlD0+ykK8L7RcE1u5hVjrWTOib/FkwRXFH+HpD7iQKSpoYsAUUBSu2y+PXeujZD\nQH7NraR719xmJnddYZ0IqRCe8nzA9ilaOayMWX9/Ovw8hqy3OMA4gaJaHOaKrzr1\nt29Ek/xc1Ej3LbfSiKX5OkUR88Z++ezx2kuMAuGqx8ZotK6LiLOJuabDtiv8KIM1\nYJmpwWEOpB6jkEcRQFVbuULDeTwAQXMqu2jMYIej7GSypuL9Y8VNud3v+wZ6wGnX\n/dK1f/djNDKp2wT2tWgp2SqBtIwLYYQh+bInnoHXQ9OMvdSmX/QSh8UTC8BrWOEr\nEpNpWvLLAgMBAAECggEAVofh601ttjaClsIqrO8AocVeG6LbqZcpXMz+OzeXUiAT\nb/ZtXCy0VfvkMI1RadVYEOUsvP9gDS0cb0kGKknjTwZ98b/83N3AclGKp/vgLL1H\nm8BzjMU3e8PDD5N4UNEXn2NLidc4HQkuCoSpimdEFBE+SNb0yLgEiVbSn+hj7C7P\nNeH6uG+PfuhN2qctSYQE2wX+OSIYbEQ0LQIHCMrXtpE8Zon+//Nsd7zRdYprKwXQ\nystBIOT0uKW3lw4Rd2euP/4ocEN54NqWJHwAuo6hiGNI1s/VHeCoVM7xNQ9p70b+\ncbSzNj0IbRhLXiEGQvcStvhHuSGJIJkDZnpshgirIQKBgQDYx1TRHoAI+HMTDY2f\n9R353wzOFd/3sx7SaoOoDlvLDiC/slIN1EMUDGfhDJ/zlCYFKqsXXDj01GZHxRq1\nFEZTvB91jGEYp7yhAQj2LCtQzq0aft5AcACWr67xSe7pyUFl8kSRRMmBBdZbUYnK\n10EfvniQ5oJTQRCM3pX7o5WO6wKBgQDVCGcwIdUL6BlrKT3NTvn28xNHvNrJ3D68\nt3rou3Aiu5/edBu8aJLI7sq2co4dETsjNM/u1iubiykY3stleSZz+lDZV7256mHv\nOiI/Oc++4Djb4azN3GOR4rtrkpLx/SCD4BzeLxjZPXfn3Z26c6OJb+4izgjdTYJ+\nWOgkiinzoQKBgAuMGq2FBWb07RRPvYKOyQj9Y646phKIvRSSTe8OzL71QrNTaWGJ\nNAWGX6YySPbtplTSIAj/hZ0tD0G1cyXALbraI4bccnOgw8CD0JlkYu5MBBaMOYSP\nMsjUFOqPeKWFbfFjRVnDo0Q3LmLw5fkjHDn3qG53iOusZJhMZwrffOD/AoGBAMt0\nEQiY5x1N9yiu5IU1zeiZUWqL5PAwVgJpwQqQKJIjWpVbkjmoLbeUxyjj0vHTyQTg\npU1WYaNVjlRgQySQRbcx8xD/iQUL4ahVfuufTNbg0ay9pQmeV8G2JoSgIZLWyrzn\nxuozVKn02JUqxD6TvjW+HlJDL5gbNGtygZKUGWjBAoGBANhamdZ93+8EQb5FXPqq\n8d5FDcAJ0zQ9AA/8e63seIF5YudlR0uI94pc6cb63zHCnc+DfqqFfOhG/5B0e2el\nTqWUfw6HqKQZRRWrtCm6I6zM4IRuDNsYyozyOwxhg27eHp4JUrbm0J+BqubL/uiC\nkdGykZWwsil8VlepZMdSUTiU\n-----END PRIVATE KEY-----\n"
SUPABASE_URL="https://ealltigixccmzpyozrxl.supabase.co"
SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhbGx0aWdpeGNjbXpweW96cnhsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MjA0MzQzMCwiZXhwIjoyMDk3NjE5NDMwfQ.KRMDr5vzzo_vDjlqmyxuqz06GH69tWt_B2J2CUUb-0Y"
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1